### PR TITLE
Fixing problems for tvshows and custom folder

### PR DESCRIPTION
**Pull request by frankdpGH**
Hi Luizoti, 
Interesting tool, should be brought alive again for matrix...
I did some testing to make the tvshows work again.
Some minor changes / error corrections. (xbmc lib missing, join list, messages, regex for nt) 
Custom location for the "managed.db" I have made a fixed location in the addon folder to avoid SQL problems.  Tested common library on smb server and this is also working now. Tested on windows, linux and android.
Thanks for creating a new version.

### CODE REVIEW

**Review by luizoti — COMMENTED** [review]
What's the point of importing xbmc here (and in other modules that don't use it)?

**Review by luizoti — COMMENTED** [review]
All these strings need to be included in the language files in [language](https://github.com/luizoti/script.library.integration.tool/tree/Matrix/resources/language)

Some other strings that need review are here:

https://github.com/luizoti/script.library.integration.tool/issues/22

As they are about to be revised, they may or may not exist in any of the language files, I don't remember if they are included, but if they are not, it is necessary to put them in both.

To use them, use the method: getstring(string_id).

Before including, if you do, check if you are not repeating the string (in both files) and if it makes sense when translated, in this case, it can be sent for review via PR, at least it makes sense to me.

**Comment by frankdpGH** [comment]
Hi luizoti, sorry about the quality errors. Based on the quality report https://app.codacy.com/gh/luizoti/script.library.integration.tool/pullRequest?prid=9431133 
I have made the corrections on my fork side. How do we proceed ? Delete this PR and I create a new PR?

**Review by luizoti — CHANGES_REQUESTED** [review]
Try to remove unused import by this request.

**Review by frankdpGH — COMMENTED** [review]
Yes Perfect , Thx!
I suppose now up to you to approve the changes.

**Comment by luizoti** [comment]
Man, I don't know if anything has changed, let's do it like this I'll cancel this PR and you send another one, I really don't know if I can reject just one or another commit keeping the correct ones.

**Pull request closed without merging**
