### PR TITLE
Fixing problems for tvshows and custom folder

### PR DESCRIPTION
**Pull request by frankdpGH**
Hi Luizoti,
I did some testing to make the tvshows work again.
Some minor changes / error corrections. (xbmc lib missing, join list, messages, regex for nt)
Custom location for the "managed.db" I have made a fixed location in the addon folder to avoid SQL problems. Tested common library on smb server and this is also working now. Tested on windows, linux and android.
Thanks for creating a new version.

### CODE REVIEW

**Comment by luizoti** [comment]
You sent a PR equal to the previous one.

**Comment by frankdpGH** [comment]
> You sent a PR equal to the previous one.

The changes are correct, you closed the other without merging....

**Comment by luizoti** [comment]
If it was correct I would have merged it in the first PR.

**Comment by luizoti** [comment]
Fechado, aguardando reenvio com a correção do commits com mudanças desnecessários ou 100% irrelevantes no momento, os demais commits com mudanças relacionadas ao banco de dados e etc, serão analisados em um próximo e correto commit.

**Pull request closed without merging**
